version: '3.7'
services:
  db_psql:
    image: postgres:11-alpine
    container_name: golaxy_psql
    ports:
      - "5432:5432"
    volumes:
      - ./db/psql:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: golaxy_admin
      POSTGRES_PASSWORD: supermassive_black_hole
      POSTGRES_DB: golaxy
      PGDATA: /var/lib/postgresql/data/pgdata